#!/usr/bin/expect
set timeout 600
set results [lindex $argv 0]
set description [lindex $argv 1]
spawn phoronix-test-suite batch-setup

expect "Save test results when in batch mode (Y/n): "
send "Y\r"
expect "Open the web browser automatically when in batch mode (y/N): "
send "N\r"

expect "Auto upload the results to OpenBenchmarking.org (Y/n): "
send "n\r"

expect "Prompt for test identifier (Y/n): "
send "Y\r"


expect "Prompt for test description (Y/n): "
send "Y\r"

expect "Prompt for saved results file-name (Y/n): "
send "Y\r"

expect "Run all test options (Y/n): "
send "n\r"

spawn phoronix-test-suite batch-benchmark pts/tiobench 
expect "Test:"
send "2\r"

expect "Size Per Thread:"
send "2\r"

expect "Thread Count:"
send "4\r"

expect "Enter a name to save these results under: "
send "$results\r"

expect "Enter a unique name to describe this test run / configuration: "
send "$description\r"

expect "New Description: "
send "$description\r"

interact
